### ISSUE TITLE
Support RSA keysizes other than 2048

### ISSUE THREAD

**Issue by promovicz** [Yubico/ykneo-openpgp#29] opened 2015-04-29 12:25 UTC
It would be nice to support at the very least 4096 bit keys, but 1024 bit might also still be interesting for compatibility purposes.

While most JavaCard cards (just as the YKNEO) do not support more than 2048 bits there are various cards on the market which do, even though most of them require signing an NDA or other considerations.

I have access to one such device, and it would be nice to clean up the code so it can deal with arbitrary RSA key sizes, as supported by the card.

**Comment by klali** [comment] 2015-04-29 12:40
There is some code to this effect on the branch devel/key_attributes

**Comment by JHGitty** [comment] 2015-05-04 23:46
@promovicz Why are JavaCard cards with 4096bit support under NDA?

**Comment by klali** [comment] 2015-05-05 06:28
closing this as a duplicate of #2

**Closed by klali** 2015-05-05 06:28 UTC

**Comment by promovicz** [comment] 2015-05-05 16:38
@JHGitty There is no reason per-se for that. Actually all smartcard processors (except for some chinese ones) I know of require an NDA for proper documentation. The issue with 4096bit cards is that they simply aren't marketed to end users, and working with them commercially will often require an NDA just to know the exact features of the card...

**Comment by seefood** [comment] 2017-04-04 12:46
Almost two years later, is it safe to say no RSA4096 NEO is around the corner, and if it comes it won't be FOSS?

**Comment by jonathancross** [comment] 2017-04-24 18:44
@seefood The non-FOSS [YubiKey-4](https://www.yubico.com/products/yubikey-hardware/) supports RSA4096, but there is no indication that the FOSS Yubikey NEO will ever support > 2048.

**Comment by seefood** [comment] 2017-04-25 13:02
So if I want a FOSS key that supports RSA4096 I guess it won't do u2f and cost more. bleh. I guess I'll go for a NEO and source the PGP functionality elsewhere.
